# CONNECTION_ERROR_ATTEMPTS = 20
CONNECTION_ERROR_ATTEMPTS = 10
# NON_DET_ERROR_ATTEMPTS = 5
NON_DET_ERROR_ATTEMPTS = 20
ERROR = 'ERROR'

# ---------------------------------------

# SCAN_MIN_ATTEMPTS = 10
SCAN_MIN_ATTEMPTS = 20
# SCAN_MAX_ATTEMPTS = 200
SCAN_MAX_ATTEMPTS = 100
PHYSICAL_RESET = False

# ---------------------------------------

NON_DET_CACHE_SIZE = 20
# NON_DET_CACHE_THRESHOLD = 6
NON_DET_CACHE_THRESHOLD = 6
NON_DET_CEX_CACHE_SAMPLE = 30
NON_DET_CEX_CACHE_THRESHOLD = 10
NON_DET_RESAMPLE_THRESHOLD = 8
NON_DET_RESAMPLE_COUNT_THRESHOLD = 2

NONDET_QUERY_NUMBER = 10
NONDET_THRESHOLD = 3

# ---------------------------------------

# CONNECT_MIN_ATTEMPTS = 50
# CONNECT_MAX_ATTEMPTS = 100
CONNECT_MIN_ATTEMPTS = 30
CONNECT_MAX_ATTEMPTS = 70
TERMINATE_MIN_ATTEMPTS = 1
TERMINATE_MAX_ATTEMPTS = 1
MIN_ATTEMPTS = 10
MAX_ATTEMPTS = 20
LOG_PCAP = True
MAX_FUZZING_CEX_REPETITIONS = 5

# ---------------------------------------

PAIRING_REQUEST_FLAG = True
ERROR_HANDLING_FLAG = 10
QERY_THRESHOLD_UNTIL_RESET = 500

# ---------------------------------------

DIFFERENCE_CHECKER_DEVICE_THRESHOLD = 0.3
DIFFERENCE_THRESHOLD = 0.6
DIFFERENCE_BOUND_WIDTH = 0.2
OVERALL_DIFFERENCE = 0.7
